# name = input("Please enter your name: ")
# print(name)

# num1 = input("Enter a number: ")
# print(num1)
# print(type(num1))
# num2 = input("Enter a number: ")
# print(num2)
# print(num1 + num2)

num1 = int(input("Enter a number: "))
print(type(num1))
num2 = float(input("Enter a number: "))
print(type(num2))
print(num1 + num2)